apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  workspaces:
    - name: output

  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
      default: main
    - name: build-image
      type: string
    - name: app-name
      type: string

  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: git-clone
      runAfter: [cleanup]
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: output

    - name: eslint
      runAfter: [git-clone]
      taskRef:
        name: eslint
      workspaces:
        - name: source
          workspace: output

    - name: jest-test
      runAfter: [eslint]
      taskRef:
        name: jest-test
      workspaces:
        - name: source
          workspace: output

    - name: buildah
      runAfter: [jest-test]
      taskRef:
        kind: ClusterTask
        name: buildah
      params:
        - name: IMAGE
          value: $(params.build-image)
      workspaces:
        - name: source
          workspace: output

    - name: deploy
      runAfter: [buildah]
      taskRef:
        kind: ClusterTask
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -